//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ACTIVITY_LOG
{
    public string ID { get; set; }
    public string ACTIVITY_CODE { get; set; }
    public string DATE_TIME { get; set; }
    public string REMARK { get; set; }
    public int UNIQUE_ID { get; set; }
}

public partial class AMAZON
{
    public string Code { get; set; }
}

public partial class CHAT_NOTICE
{
    public int MESSAGE_ID { get; set; }
    public int PARTICIPANT_ID { get; set; }
    public string DESIGNATION { get; set; }
}

public partial class CODEBOOK
{
    public string TYPE { get; set; }
    public string CODES { get; set; }
}

public partial class COUNSELOR
{
    public string ID { get; set; }
    public string USERNAME { get; set; }
    public string PASSWORD { get; set; }
    public string NAME_FIRST { get; set; }
    public string NAME_LAST { get; set; }
    public string EMAIL { get; set; }
    public string SITE { get; set; }
}

public partial class FOLLOWUP_RESPONSE
{
    public string PARTICIPANT_ID { get; set; }
    public string QUESTION_CODE { get; set; }
    public string RESPONSE { get; set; }
    public string DATE_TIME { get; set; }

    public virtual PARTICIPANT PARTICIPANT { get; set; }
}

public partial class FOLLOWUP_RESPONSE_B
{
    public string PARTICIPANT_ID { get; set; }
    public string QUESTION_CODE { get; set; }
    public string RESPONSE { get; set; }
    public string DATE_TIME { get; set; }

    public virtual PARTICIPANT PARTICIPANT { get; set; }
}

public partial class GRID_REF
{
    public GRID_REF()
    {
        this.QUESTION_REF = new HashSet<QUESTION_REF>();
    }

    public int gid { get; set; }
    public int pid { get; set; }
    public string title { get; set; }
    public int g_rank { get; set; }

    public virtual ICollection<QUESTION_REF> QUESTION_REF { get; set; }
    public virtual PAGE_REF PAGE_REF { get; set; }
}

public partial class MESSAGE
{
    public int ID { get; set; }
    public string FROM_ID { get; set; }
    public string TO_ID { get; set; }
    public string MESSAGE_BODY { get; set; }
    public string DATE_TIME { get; set; }
    public Nullable<int> RESPONDING_TO { get; set; }
    public string REMARK { get; set; }
}

public partial class MESSAGE_ALT
{
    public int ID { get; set; }
    public string FROM_ID { get; set; }
    public string TO_ID { get; set; }
    public string MESSAGE_BODY { get; set; }
    public System.DateTime DATE_TIME { get; set; }
    public Nullable<int> RESPONDING_TO { get; set; }
    public string REMARK { get; set; }
}

public partial class ONLINE_STATUS
{
    public string ID { get; set; }
    public string DESIGNATION { get; set; }
    public string DATE_TIME { get; set; }
    public string SITE { get; set; }
}

public partial class PAGE_REF
{
    public PAGE_REF()
    {
        this.GRID_REF = new HashSet<GRID_REF>();
        this.QUESTION_REF = new HashSet<QUESTION_REF>();
    }

    public int pid { get; set; }
    public string title { get; set; }
    public string imageurl { get; set; }
    public string value { get; set; }
    public string survey { get; set; }
    public string hard_prompt { get; set; }

    public virtual ICollection<GRID_REF> GRID_REF { get; set; }
    public virtual ICollection<QUESTION_REF> QUESTION_REF { get; set; }
}

public partial class PARTICIPANT
{
    public PARTICIPANT()
    {
        this.FOLLOWUP_RESPONSE = new HashSet<FOLLOWUP_RESPONSE>();
        this.FOLLOWUP_RESPONSE_B = new HashSet<FOLLOWUP_RESPONSE_B>();
        this.SCREENING_RESPONSE = new HashSet<SCREENING_RESPONSE>();
    }

    public string ID { get; set; }
    public string NAME_FIRST { get; set; }
    public string GENDER { get; set; }
    public string EMAIL { get; set; }
    public string PASSWORD { get; set; }
    public Nullable<short> YEAR { get; set; }
    public string REMARK { get; set; }

    public virtual ICollection<FOLLOWUP_RESPONSE> FOLLOWUP_RESPONSE { get; set; }
    public virtual ICollection<FOLLOWUP_RESPONSE_B> FOLLOWUP_RESPONSE_B { get; set; }
    public virtual ICollection<SCREENING_RESPONSE> SCREENING_RESPONSE { get; set; }
}

public partial class QUESTION_REF
{
    public QUESTION_REF()
    {
        this.RESPONSE_X_QUESTION = new HashSet<RESPONSE_X_QUESTION>();
    }

    public int qid { get; set; }
    public int pid { get; set; }
    public string content { get; set; }
    public string value { get; set; }
    public string hidden { get; set; }
    public Nullable<int> revealed_by { get; set; }
    public Nullable<int> grid_id { get; set; }
    public string hint { get; set; }
    public string layout { get; set; }

    public virtual GRID_REF GRID_REF { get; set; }
    public virtual PAGE_REF PAGE_REF { get; set; }
    public virtual ICollection<RESPONSE_X_QUESTION> RESPONSE_X_QUESTION { get; set; }
}

public partial class RESOURCE_LINK
{
    public string SITE_ID { get; set; }
    public string URL_TEXT { get; set; }
    public string URL { get; set; }
    public string ADDTL_TEXT { get; set; }
    public System.DateTime DATE_TIME { get; set; }
    public int RANK { get; set; }
    public string ACTIVE { get; set; }
    public string CREATED_BY { get; set; }
    public int RID { get; set; }
}

public partial class RESPONSE_REF
{
    public RESPONSE_REF()
    {
        this.RESPONSE_X_QUESTION = new HashSet<RESPONSE_X_QUESTION>();
    }

    public int rid { get; set; }
    public string content { get; set; }
    public string value { get; set; }
    public string input_type { get; set; }

    public virtual ICollection<RESPONSE_X_QUESTION> RESPONSE_X_QUESTION { get; set; }
}

public partial class RESPONSE_X_QUESTION
{
    public int rid { get; set; }
    public int qid { get; set; }
    public string hidden { get; set; }
    public string excludes { get; set; }
    public string includes { get; set; }

    public virtual QUESTION_REF QUESTION_REF { get; set; }
    public virtual RESPONSE_REF RESPONSE_REF { get; set; }
}

public partial class SCHEDULE
{
    public int UNIQUE_ID { get; set; }
    public Nullable<System.DateTime> datetime_start { get; set; }
    public Nullable<System.DateTime> datetime_end { get; set; }
    public string participant_id { get; set; }
    public string couselor_id { get; set; }
}

public partial class SCREENING_RESPONSE
{
    public string PARTICIPANT_ID { get; set; }
    public string QUESTION_CODE { get; set; }
    public string RESPONSE { get; set; }
    public string DATE_TIME { get; set; }

    public virtual PARTICIPANT PARTICIPANT { get; set; }
}

public partial class SITE
{
    public string ID { get; set; }
    public string HOURS { get; set; }
    public System.DateTime DATE_TIME { get; set; }
    public int SID { get; set; }
}

public partial class STATUS
{
    public int UNIQUE_ID { get; set; }
    public string ID { get; set; }
    public string STATUS_CODE { get; set; }
    public string STATUS_VALUE { get; set; }
    public string DATE_TIME { get; set; }
}
